version: '3.7'

services:
  db:
    container_name: valoriza_mariadb
    image: wodby/mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:3306

  adminer:
    container_name: valoriza_adminer
    image: wodby/adminer:latest
    depends_on:
      - db
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: ${DATABASE_NAME}
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter
    ports:
      - "${ADMINER_PORT:-9000}:9000"
